version: '3'

services:
  dev:
    image: node:18
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on: 
      - target
    networks:
      - web-monitor-dev
  infra-test:
    image: node:18
    working_dir: /app
    command: yarn test:infrastructure
    environment:
      - CONFIG
    volumes:
      - ./:/app
    restart: "no"
    depends_on: 
      - target
    networks:
      - web-monitor-dev
  target:
    image: httpd:2.4
    restart: unless-stopped
    volumes:
      - ./tests/infrastructure/httpd:/usr/local/apache2/conf/docker
    networks:
      web-monitor-dev:
        aliases:
          - target
          - target2
    command: /usr/local/apache2/conf/docker/entrypoint.sh
  mail:
    image: tecnativa/smtp-sink
    restart: unless-stopped
    networks:
      - web-monitor-dev

networks:
  web-monitor-dev:
