name: CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install
    - run: yarn test:types
    - run: yarn test:unit
    - run: yarn test:integration
    - name: yarn test:infrastructure
      env:
        CONFIG: ${{ secrets.CONFIG }}
      run: >
        docker-compose \
          -f docker-compose.dev.yml up \
          --abort-on-container-exit \
          --exit-code-from=infra-test \
          infra-test

  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup config file
        run: |
          echo "ewogICJtb25pdG9ycyI6IHt9LAogICJub3RpZnkiOiB7CiAgICAiYWRtaW4iOiB7CiAgICAgICJlbWFpbCI6ICJhZG1pbkBleGFtcGxlLmNvbSIKICAgIH0KICB9LAogICJlbWFpbF9ub3RpZmllciI6IHsKICAgICJob3N0IjogIm1haWwiLAogICAgInBvcnQiOiAyNSwKICAgICJhdXRoIjogeyAidXNlciI6ICJtciIsICJwYXNzIjogImZvbyIgfQogIH0KfQo" \
            > ./config/config.yml
      - 
        name: docker-compose up (build)
        run: docker-compose -f docker-compose.ci.yml up --build --exit-code-from=monitor monitor

  release:
    needs: 
      - test
      - test-docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn release
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
