name: Unit & Infrastructure Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Yarn install
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: Check typing
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: test:types
    - name: Unit tests
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: test:unit
    - name: Integration tests
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: test:integration
    - name: Infrastructure tests
      run: >
        docker-compose \
          -f docker-compose.dev.yml up \
          --abort-on-container-exit \
          --exit-code-from=infra-test \
          infra-test
